Add basic doc to help contributers to add and test new modules
fusor/ansible-asb-modules pull request #10
Opened 2018-01-24 12:17 UTC by maleck13

@rthallisey Basic doc outlining what I learned as I was writing the module. Not sure how much detail to go into about the broker etc.

2018-01-24 13:28 UTC, rthallisey approved these changes

2018-01-24 13:28 UTC, rthallisey commented
thanks @maleck13

2018-01-24 14:19 UTC, jmrodri requested changes
Some terminology changes. Request for some additional example commands.

Excellent document. Super helpful.

2018-01-24 14:19 UTC, jmrodri commented on docs/add-new-modules.md
> +This document will cover the basics of creating a new apb module and testing the module.
change apb to APB

2018-01-24 14:19 UTC, jmrodri commented on docs/add-new-modules.md
> +Modules go under the library folder and should be named after the module they provide. For example the module for providing a last_operation update is named: ```asb_last_operation.py```
escape library with single backtick: `library`

2018-01-24 14:19 UTC, jmrodri commented on docs/add-new-modules.md
> +The apb modules are intended to run from within the context of a Docker image as part of a POD running in a Kubernetes or Openshift environment. They regularly will need to interact with resources cr
apb -> APB
Openshift -> OpenShift

2018-01-24 14:19 UTC, jmrodri commented on docs/add-new-modules.md
> +4) Build a new image and push it to your docker org
Are there commands you could include as examples to show how you built and pushed the image?

2018-01-24 14:19 UTC, jmrodri commented on docs/add-new-modules.md
> +5) Ensure your ansible service broker is configured to look for apbs in the docker org where you have pushed the test apb
change ansible service broker to Ansible Broker.
apbs -> APBs

2018-01-24 14:19 UTC, jmrodri commented on docs/add-new-modules.md
> +To debug the module, you can login to your cluster as a cluster admin then view the logs of the apb pod that is created, if there is a problem with your module, these logs should give you insight int
I would include some sample commands. Sometimes I want to get into a technology without fulling knowing what's going on and need reminders of the commands to use.

```
oc login -u system:admin
oc project ansible-service-broker
oc logs asb-1-deadf
```
something like that would be helpful.

2018-01-24 16:07 UTC, maleck13 commented
@jmrodri take 2 :)

2018-02-07 21:21 UTC, maleck13 commented
@jmrodri you ok with this doc now? I think it adds value and would be good to merge

2018-02-07 21:34 UTC, rthallisey commented
It's looks like all the comments have been addressed and it's been around enough time for further comments.  I'm going to go ahead and merge it.

2018-02-07 21:34 UTC, merged