adding the save_test_result module.
fusor/ansible-asb-modules pull request #3
Opened 2017-08-16 19:38 UTC by shawn-hurley

Tied to proposal https://github.com/fusor/ansible-playbook-bundle/pull/92

2017-08-16 19:57 UTC, jwmatthews commented on library/asb_save_test_result.py
> +      - 'Will signify whether the test result has passed or faild.'
s/faild/failed

2017-08-16 19:57 UTC, jwmatthews commented on library/asb_save_test_result.py
> +      - 'Determines the message th should be displayed for the failure or
'th' seems strange

2017-08-16 20:09 UTC, shawn-hurley commented on library/asb_save_test_result.py
> +      - 'Determines the message th should be displayed for the failure or
Updated the wording completely

2017-08-16 20:14 UTC, cfchase requested changes

2017-08-16 20:14 UTC, cfchase commented on library/asb_save_test_result.py
> +        ansible_module.fail_json(msg="Error attempting to write binding: " + str(error))
s/binding/"test result"

2017-08-16 20:14 UTC, cfchase commented on library/asb_save_test_result.py
> +import base64
unnecessary import?

2017-08-16 20:14 UTC, cfchase commented on tests/test_asb_save_test_result.yml
> +    - name: encode bind credentials
might want to rename anywhere you use the word bind

2017-08-16 20:14 UTC, cfchase commented on tests/test_asb_save_test_result.yml
> +
Just wondering what the expected/actual behavior is if you do multiple test results.  Will it append new messages to the same file or will it overwrite the original file?  Seems like we'd want multiple test results to show in the file.

2017-08-17 12:43 UTC, shawn-hurley commented on tests/test_asb_save_test_result.yml
> +
I had thought that we would want to overwrite. But I think your right, that multiple results should be saved.

2017-08-17 14:58 UTC, cfchase commented on tests/test_asb_save_test_result.yml
> +    - name: read credentials file
You might want to change all the mentions of "credentials" or "encoded" in this file.  Other than that nitpick, the PR looks good to me.

2017-08-17 15:08 UTC, cfchase approved these changes

2017-08-17 15:18 UTC, shawn-hurley commented
Wait to merge for https://github.com/fusor/ansible-playbook-bundle/pull/92 to merge in

2017-08-21 13:14 UTC, shawn-hurley commented
![](https://github.trello.services/images/mini-trello-icon.png) [(13) Add ability for APB to test itself using a test action.](https://trello.com/c/D9l82yol/426-13-add-ability-for-apb-to-test-itself-using-a-test-action)

2017-08-30 14:19 UTC, merged